# Generated by Django 4.2.29 on 2026-04-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('search_terms', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField()),
                ('title', models.CharField(max_length=300)),
                ('url', models.TextField()),
                ('img_url', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('searches', models.ManyToManyField(blank=True, related_name='posts', to='api.search')),
            ],
        ),
    ]
